from pathlib import Path
import pytest


@pytest.fixture(scope="session", autouse=True)
def cleanup_compiled_models():
    """Clean up .py files generated by XMILE compilation after the test session."""
    yield
    test_models_dir = Path(__file__).parent / "test_models"
    for file_path in test_models_dir.glob("*.py"):
        file_path.unlink()
